name: Deploy to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Deploy files to cPanel public_html via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.6
        with:
          server: www.milestoneschoolzambia.com
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          ssh_private_key: ""
          port: 22
          sftp_only: true
          local_path: "./*"
          remote_path: "/home/mileston/public_html"

